USER feelpp
ENV HOME /home/feelpp

# Source config for further use
RUN bash -c 'echo -e "# Source configuration for Feel++\nsource $HOME/feelpp.conf.sh" >> ${HOME}/.bashrc'

# Install Feel++
RUN bash -c 'echo CC=${CC} -- CXX=${CXX}'
RUN bash -c 'echo CMAKE_FLAGS=${CMAKE_FLAGS}'
RUN bash -c 'echo CXXFLAGS=${CXXFLAGS}'
RUN bash -c "source $HOME/feelpp.conf.sh && install_feelpp_libs ${BRANCH} ${BUILD_JOBS} ${CMAKE_FLAGS}"

COPY WELCOME.libs $HOME/WELCOME.libs
RUN bash -c 'cat WELCOME.libs >> WELCOME'
USER feelpp
#ENTRYPOINT ["/sbin/my_init","--quiet","--","sudo","-u","feelpp","/bin/sh","-c"]
CMD ["/bin/bash"]
