# Set up user so that we do not run as root
# Changing the password does not work on certain OS and is not needed
# echo "feelpp:docker" | chpasswd && \
RUN useradd -m -s /bin/bash -G sudo feelpp && \
    echo "feelpp ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

ENV HOME /home/feelpp

# Our helper scripts
COPY feelpp.env.sh $HOME/feelpp.env.sh
COPY feelpp.conf.sh $HOME/feelpp.conf.sh

# and the README
COPY WELCOME $HOME/WELCOME
RUN chown feelpp:feelpp $HOME/WELCOME && \
    chown feelpp:feelpp $HOME/feelpp.env.sh && \
    chown feelpp:feelpp $HOME/feelpp.conf.sh && \
    chmod u+rw $HOME/WELCOME && \
    chmod u+rw $HOME/feelpp.env.sh && \
    chmod u+rw $HOME/feelpp.conf.sh 

# OpenBLAS threads should be 1 to ensure performance
RUN echo "export OPENBLAS_NUM_THREADS=1" >> $HOME/.bashrc && \
    echo "export OPENBLAS_VERBOSE=0" >> $HOME/.bashrc

# This makes sure we launch with ENTRYPOINT /bin/bash into the home directory
RUN echo "export FEELPP_DEP_INSTALL_PREFIX=${FEELPP_DEP_INSTALL_PREFIX}" >> $HOME/.bashrc && \
    echo "export CC=$CC" >> $HOME/.bashrc && \
    echo "export CXX=$CXX" >> $HOME/.bashrc && \
    echo "source $HOME/feelpp.env.sh" >> $HOME/.bashrc && \
    echo "source $HOME/feelpp.conf.sh" >> $HOME/.bashrc && \
    echo "cd $HOME" >> $HOME/.bashrc && \
    echo "cat $HOME/WELCOME" >> $HOME/.bashrc

USER feelpp
#ENTRYPOINT ["/sbin/my_init","--quiet","--","sudo","-u","feelpp","/bin/sh","-c"]
#ENTRYPOINT ["/sbin/my_init","--quiet","--","sudo","-u","feelpp","/bin/sh","-c"]
CMD ["/bin/bash"]
