version: '2'

services:
    #feelpp-syspackages:
        #build:
            #context: ./dockerfiles/dev-env
            #dockerfile: Dockerfile.syspackages
        #image: feelpp/syspackages:latest

    feelpp-full-dev-env:
        build:
            context: ./dockerfiles/dev-env
            dockerfile: Dockerfile
            args:
                - BUILD_JOBS=32
        image: feelpp/feelpp-env:latest
        #depends_on: 
            #- feelpp-syspackages

    feelpp-minimal-dev-env:
        build:
            context: ./dockerfiles/dev-env
            dockerfile: Dockerfile
            args:
                - BUILD_JOBS=32
                - INSTALL_OPENTURNS=0
                - INSTALL_PETSC=0
                - INSTALL_SLEPC=0
                - INSTALL_GMSH=0
                - INSTALL_PARAVIEW=0
        image: feelpp/feelpp-env:minimal
        #depends_on: 
            #- feelpp-syspackages

    feelpp-full-develop:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile
        image: feelpp/develop:latest
        depends_on: 
            - feelpp-full-dev-env
