version: '2'

services:
    # Build and install full development environment with all dependencies
    feelpp-dev-env-full:
        build:
            context: ./dockerfiles/dev-env
            dockerfile: Dockerfile
            args:
                - BUILD_JOBS=32
        image: feelpp/feelpp-env:latest
            
    # Build and install full development environment with all dependencies
    feelpp-dev-env-full-ubuntu-16.04:
        build:
            context: ./dockerfiles/dev-env
            dockerfile: Dockerfile.ubuntu-16.04
            args:
                - BUILD_JOBS=32
        image: feelpp/feelpp-env:latest-ubuntu-16.04

    # Build and install minimal development environment
    feelpp-dev-env-minimal:
        build:
            context: ./dockerfiles/dev-env
            dockerfile: Dockerfile
            args:
                - BUILD_JOBS=32
                - INSTALL_OPENTURNS=0
                - INSTALL_PETSC=0
                - INSTALL_SLEPC=0
                - INSTALL_GMSH=0
                - INSTALL_PARAVIEW=0
        image: feelpp/feelpp-env:minimal

    # Build and install Feel++ without specific options
    feelpp-develop-full:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile.dockerhub
            args:
                - BUILD_JOBS=32
                - CMAKE_FLAGS=""
        image: feelpp/develop:latest
        depends_on:
            - feelpp-dev-env-full

    # Build and install Feel++ with In-situ support
    feelpp-develop-full-insitu:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile.dockerhub
            args:
                - BUILD_JOBS=32
                - CMAKE_FLAGS="-DFEELPP_ENABLE_VTK_INSITU=ON"
        image: feelpp/develop:insitu
        depends_on:
            - feelpp-dev-env-full
              
    # Build and install Feel++ with In-situ support
    feelpp-develop-full-insitu-ubuntu-16.04:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile.dockerhub.ubuntu-16.04
            args:
                - BUILD_JOBS=32
                - CMAKE_FLAGS="-DFEELPP_ENABLE_VTK_INSITU=ON"
        image: feelpp/develop:insitu-ubuntu-16.04
        depends_on:
            - feelpp-dev-env-full

    # Build and install Feel++ without VTK
    feelpp-develop-full-novtk:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile.dockerhub
            args:
                - BUILD_JOBS=32
                - CMAKE_FLAGS="-DFEELPP_ENABLE_VTK=OFF"
        image: feelpp/develop:novtk
        depends_on:
            - feelpp-dev-env-full

    # Build and install Feel++ and the fluid model apps
    feelpp-develop-models-fluid:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile.apps
            args:
                - BUILD_JOBS=32
                - CMAKE_FLAGS="-DFEELPP_ENABLE_VTK_INSITU=ON"
                - APP_INSTALL_CMD="install_feelpp_models_fluid"
        image: feelpp/develop:models-fluid
        depends_on:
            - feelpp-dev-env-full

    # Build and install Feel++ and the solid model apps
    feelpp-develop-models-solid:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile.apps
            args:
                - BUILD_JOBS=32
                - CMAKE_FLAGS="-DFEELPP_ENABLE_VTK_INSITU=ON"
                - APP_INSTALL_CMD="install_feelpp_models_solid"
        image: feelpp/develop:models-solid
        depends_on:
            - feelpp-dev-env-full

    # Build and install Feel++ and the fsi model apps
    feelpp-develop-models-fsi:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile.apps
            args:
                - BUILD_JOBS=32
                - CMAKE_FLAGS="-DFEELPP_ENABLE_VTK_INSITU=ON"
                - APP_INSTALL_CMD="install_feelpp_models_fsi"
        image: feelpp/develop:models-fsi
        depends_on: 
            - feelpp-dev-env-full
              #
    # Build and install Feel++ and the CRB apps
    #feelpp-develop-crb-apps:
        #build:
            #context: ./dockerfiles/develop
            #dockerfile: Dockerfile.apps
            #args:
                #- BUILD_JOBS=32
                #- CMAKE_FLAGS="-DFEELPP_ENABLE_VTK_INSITU=ON"
                #- APP_INSTALL_CMD="install_feelpp_crb_apps"
        #image: feelpp/develop:crb
        #depends_on: 
            #- feelpp-dev-env-full
