version: '2'

services:
    #feelpp-syspackages:
        #build:
            #context: ./dockerfiles/dev-env
            #dockerfile: Dockerfile.syspackages
        #image: feelpp/syspackages:latest

    feelpp-dev-env-full:
        build:
            context: ./dockerfiles/dev-env
            dockerfile: Dockerfile
            args:
                - BUILD_JOBS=32
        image: feelpp/feelpp-env:latest
        #depends_on: 
            #- feelpp-syspackages

    feelpp-dev-env-minimal:
        build:
            context: ./dockerfiles/dev-env
            dockerfile: Dockerfile
            args:
                - BUILD_JOBS=32
                - INSTALL_OPENTURNS=0
                - INSTALL_PETSC=0
                - INSTALL_SLEPC=0
                - INSTALL_GMSH=0
                - INSTALL_PARAVIEW=0
        image: feelpp/feelpp-env:minimal
        #depends_on: 
            #- feelpp-syspackages

    feelpp-develop-full:
        build:
            context: ./dockerfiles/develop
            dockerfile: Dockerfile.dockerhub
            args:
                - BUILD_JOBS=32
                - CMAKE_FLAGS="-DFEELPP_ENABLE_VTK_INSITU=ON"
        image: feelpp/develop:latest
        depends_on: 
            - feelpp-dev-env-full
