# -*- mode: Dockerfile -*-

FROM debian:buster

ARG CHANNEL
ENV CHANNEL=${CHANNEL:-latest}
RUN apt-get update \
        && apt-get install -y \
        vim \
        ssh \
        sudo \
        wget \
        gnupg2 \
        software-properties-common ;\
        rm -rf /var/lib/apt/lists/*

RUN useradd --user-group --create-home --shell /bin/bash feelpp ;\
        echo "foam ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

        

RUN wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | apt-key add -;\
        echo "deb https://dl.bintray.com/feelpp/debian buster ${CHANNEL}" | tee -a /etc/apt/sources.list;\
        apt-get update ;\
        apt-get install -y --no-install-recommends feelpp-toolboxes feelpp-toolboxes-data feelpp-tools \
                        python3-feelpp-toolboxes python3-mpi4py python3-sympy python3-pip python3-feelpp-mor \
                        python3-setuptools git cmake;\
        rm -rf /var/lib/apt/lists/* ;

RUN     echo "export FEELPP_REPOSITORY=/feel" >> ~feelpp/.bashrc;\
        echo "export OMPI_MCA_btl_vader_single_copy_mechanism=none" >> ~feelpp/.bashrc

USER feelpp
