# -*- mode: Dockerfile -*-

FROM debian:buster

ARG CHANNEL
ENV CHANNEL=${CHANNEL:-latest}
RUN apt-get update \
        && apt-get install -y \
        vim \
        ssh \
        sudo \
        wget gpg \
        software-properties-common ;\
        rm -rf /var/lib/apt/lists/*

RUN useradd --user-group --create-home --shell /bin/bash feelpp ;\
        echo "feelpp ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

ENV DEBIAN_FRONTEND=noninteractive        
RUN     apt-get -qq update; \
        apt-get -y install tzdata dos2unix; \
        wget -qO - http://apt.feelpp.org/apt.gpg | apt-key add; \
        echo "deb http://apt.feelpp.org/$FLAVOR $VARIANT ${CHANNEL}" | tee -a /etc/apt/sources.list.d/feelpp.list; \
        apt-get update ;\
        apt-get install -y --no-install-recommends feelpp-quickstart feelpp-data feelpp-tools python3-feelpp make rsync g++; \
        rm -rf /var/lib/apt/lists/* ;

RUN     echo "export FEELPP_REPOSITORY=/feel" >> ~feelpp/.bashrc;\
        echo "export OMPI_MCA_btl_vader_single_copy_mechanism=none" >> ~feelpp/.bashrc

USER feelpp
