RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    software-properties-common python-software-properties
    
RUN add-apt-repository ppa:ubuntu-toolchain-r/test

RUN (for deb in deb deb-src; do echo "$deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main"; done | sudo tee /etc/apt/sources.list.d/llvm-toolchain.list)
RUN (for deb in deb deb-src; do echo "$deb http://ppa.launchpad.net/beineri/opt-qt562-xenial/ubuntu xenial main"; done | sudo tee /etc/apt/sources.list.d/qt56.list)

RUN apt-get -qq update && \
    apt-get -y --force-yes install \
         xauth cmake flex gcc-6 g++-6 gcc-7 g++-7 clang-4.0 clang++-4.0  git ipython3 openmpi-bin pkg-config \
         bash-completion \
         emacs24 emacs vim nano \      
         wget bison sudo \
         libbz2-dev \
         automake autoconf libtool\
         doxygen \
         libopenblas-dev libcln-dev libcppunit-dev \
         libgsl-dev \
         liblapack-dev libmpfr-dev \
         libopenmpi-dev libann-dev libglpk-dev \
         python3-dev libhwloc-dev libvtk6-dev libpcre3-dev \
         libhdf5-openmpi-dev libeigen3-dev libcgal-dev \
         python3-numpy python3-six python3-ply \
         python3-h5py python3-urllib3 xterm tmux screen \
         python3-pip \
         qt56-meta-full \
         gmsh libgmsh-dev \
         mongodb-server mongodb-clients libmongoc-dev libbson-dev \
         libsundials-serial-dev \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60 \
    && update-alternatives --set gcc "/usr/bin/gcc-6" \
    && update-alternatives --set g++ "/usr/bin/g++-6" \
    && update-alternatives --set cc /usr/bin/gcc \
    && update-alternatives --set c++ /usr/bin/g++ \         
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV FEELPP_DEP_INSTALL_PREFIX /usr/local

ENV Qt5_DIR /opt/qt56

