# Boost
ENV BOOST_VERSION 1.63.0
ENV BOOST_DIR boost_1_63_0
RUN if [ x$INSTALL_BOOST = x1 ]; then \
    cd /tmp \
    && wget http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/${BOOST_DIR}.tar.bz2/download -O ${BOOST_DIR}.tar.bz2 \
    && tar xjf ${BOOST_DIR}.tar.bz2 \
    && cd ${BOOST_DIR} \
    && echo "using mpi ;" >> user-config.jam \
    && echo "" >> user-config.jam \
    && ./bootstrap.sh \
    && ./bjam -j${BUILD_JOBS} install \
      --layout=tagged \
      --prefix=${FEELPP_DEP_INSTALL_PREFIX} \
      --user-config=user-config.jam \
      variant=release \
      threading=multi \
      link=shared \
    && rm -rf /tmp/* \
    ; fi

