RUN if test -f /etc/apt/sources.list; then sed -i 's/http:\/\/deb.debian.org\/debian\//http:\/\/miroir.univ-lorraine.fr\/debian\//' /etc/apt/sources.list; fi
RUN if test -f /etc/apt/sources.list; then sed -i 's/http:\/\/security.debian.org\/debian-security\//http:\/\/miroir.univ-lorraine.fr\/debian-security\//' /etc/apt/sources.list; fi




RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    software-properties-common gnupg \
    ca-certificates-java default-jre-headless \
    quilt  debhelper dh-python 

# RUN add-apt-repository ppa:ubuntu-toolchain-r/test

#RUN (for deb in deb deb-src; do echo "$deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"; done |  tee /etc/apt/sources.list.d/llvm-toolchain.list)
#RUN apt -qq update && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
RUN apt-get -y install tzdata
RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    quilt debhelper                                    \
    tree ne                                              \
    cmake                                             \
    ssh git-lfs                                                 \
    clang g++  sudo             \
    dh-python                                                   \
    python3 python3-dev python3-setuptools python3-sympy python3-pytest python3-gmsh python3-plotly python3-sklearn-pandas  python3-tqdm  \
    chrpath                                                 \
    libboost-all-dev                                    \
    libcln-dev                                                  \
    libmetis-dev libscotch-dev \
    libeigen3-dev \
    petsc-dev                                       \
    slepc-dev                                       \           
    libhdf5-openmpi-dev                                         \
    libnlopt-dev                                                \
    libgsl-dev                                                  \
    libnetcdf-dev libgl2ps-dev libglu1-mesa-dev libsm-dev libxt-dev \
    libfftw3-mpi-dev                                            \
    libxml2-dev   libpugixml-dev                                          \
    libgmsh-dev gmsh                                       \
    bison flex                                              \
    doxygen doxygen-latex                                  \
    transfig imagemagick                                    \
    libtbb-dev                                  \
    libann-dev libglpk-dev                                 \
    libbz2-dev libzip-dev                                       \
    libbson-dev                                                 \
    libmongoc-dev                                               \
    libmongoclient-dev                                          \
    python3-pymongo                                              \
    ruby-progressbar                                            \
    ruby-tilt                                                   \
    asciidoctor ruby-asciidoctor-pdf                                                 \
    libglew-dev                                                  \
    python3-h5py python3-sympy  python3-mpi4py python3-numpy python3-petsc4py-real python3-slepc4py-real  python3-venv   \
    rsync \
    docker.io jsonlint \
    man jq curl ruby ruby-dev \
    gdb\
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV FEELPP_DEP_INSTALL_PREFIX /usr/local



