# Use a base image with Spack pre-installed, or choose a base image and install Spack manually
FROM spack/ubuntu-jammy

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    python3-setuptools \
    rsync \
    libblas-dev \
    liblapack-dev

# Install Clang via Spack
RUN spack install llvm

# Install MPICH via Spack
RUN spack install -j40 mpich

# Install HDF5 and MUMPS via Spack using MPICH
RUN spack install -j40 hdf5 +mpi ^mpich \
    && spack install -j40 mumps +scotch ~metis +mpi ^mpich

# Install Gmsh via Spack
RUN spack install -j40 gmsh +oce +hdf5 ^/$(spack find --format "{hash:7}" hdf5)

# Install Boost with MPI support, using MPICH
RUN spack install -j40 boost +date_time+filesystem+iostreams+mpi+multithreaded+program_options+serialization+shared+system+test  ^mpich && spack load boost

# Install PETSc with MPI support
RUN spack install -j40 petsc +mumps ^/$(spack find --format "{hash:7}" mumps) +mpi ^mpich && spack load petsc 

# Install SLEPc
RUN spack install -j40 slepc ^/$(spack find --format "{hash:7}" petsc) && spack load slepc

# Install Python packages via Spack
RUN spack install -j40 python  && spack load python

RUN spack install -j40 py-mpi4py ^mpich
RUN spack install -j40 py-petsc4py ^/$(spack find --format "{hash:7}" petsc)
RUN spack install -j40 py-slepc4py ^/$(spack find --format "{hash:7}" slepc)
RUN spack load py-mpi4py py-petsc4py py-slepc4py

RUN spack install -j40 py-pybind11 \
    && spack install -j40 py-sympy \
    && spack install -j40 py-pytest \
    && spack install -j40 py-plotly \
    && spack install -j40 py-scikit-learn \
    && spack install -j40 py-pandas \
    && spack install -j40 py-tqdm \
    && spack install -j40 py-h5py \
    && spack install -j40 py-numpy \
    && spack load py-pybind11 py-sympy py-pytest py-plotly py-scikit-learn py-pandas py-tqdm py-h5py py-numpy

# Set the default command to launch when starting the container
CMD ["/bin/bash"]
