FROM ubuntu:16.10
MAINTAINER Feel++ Support <support@feelpp.org>



RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    software-properties-common python-software-properties
    
RUN add-apt-repository 'deb http://ubuntu.openturns.org yakkety main'

RUN apt-get -qq update && \
    apt-get -y --force-yes install \
         xauth cmake flex gcc-6 g++-6 clang-3.9 clang++-3.9  git ipython openmpi-bin pkg-config \
         bash-completion \
         emacs24 emacs vim nano \      
         wget bison sudo \
         libbz2-dev \
         automake autoconf libtool libboost-all-dev \
         doxygen \
         libopenblas-dev libcln-dev libcppunit-dev \
         libpetsc3.7-dev libslepc3.7-dev liblapack-dev libmpfr-dev \
         libopenmpi-dev libann-dev libglpk-dev \
         jq curl ruby ruby-dev \
         python-dev libhwloc-dev libvtk6-dev libpcre3-dev \
         libhdf5-openmpi-dev libeigen3-dev libcgal-dev \
         python-numpy python-vtk6 python-six python-ply \
         python-h5py python-urllib3 xterm tmux screen \
         gmsh libgmsh-dev \
         libopenturns-dev python-openturns openturns-validation openturns-examples r-other-rot\
         paraview \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN gem install rake github_changelog_generator asciidoctor  asciidoctor-bibtex jekyll jekyll-asciidoc \
 && gem install asciidoctor-latex --pre
