ARG DEBIAN_MAIN_MIRROR=ftp.fr.debian.org   # override with --build-arg if needed
#ARG DEBIAN_MAIN_MIRROR=miroir.univ-lorraine.fr
RUN set -e; \
  . /etc/os-release || true; \
  case "${ID}:${VERSION_CODENAME}" in \
    debian:bookworm|debian:trixie|debian:sid|debian:testing) \
      f=/etc/apt/sources.list.d/debian.sources; \
      echo "Switching main archive to http://${DEBIAN_MAIN_MIRROR}/debian (keeping security) in ${f}"; \
      sed -i "0,/^URIs:\s*http:\/\/deb\.debian\.org\/debian/s//URIs: http:\/\/${DEBIAN_MAIN_MIRROR}\/debian/" "$f"; \
      apt-get -qq update; \
      ;; \
    *) echo "Leaving APT sources untouched (ID=${ID} CODENAME=${VERSION_CODENAME}).";; \
  esac


RUN apt-get -qq update && \
    apt-get -y  install \
    gnupg \
    ca-certificates-java default-jre-headless \
    quilt  debhelper dh-python 

# RUN add-apt-repository ppa:ubuntu-toolchain-r/test

#RUN (for deb in deb deb-src; do echo "$deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"; done |  tee /etc/apt/sources.list.d/llvm-toolchain.list)
#RUN apt -qq update && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
RUN apt-get -y install tzdata
RUN apt-get -qq update && \
    apt-get -y  install \
    quilt debhelper                                    \
    tree ne                                              \
    cmake                                             \
    ssh git-lfs                                                 \
    clang g++  sudo             \
    dh-python                                                   \
    python3 python3-dev python3-setuptools python3-sympy python3-pytest python3-gmsh python3-plotly python3-sklearn-pandas  python3-tqdm  \
    chrpath                                                 \
    libboost-all-dev                                    \
    libcln-dev                                                  \
    libmetis-dev libscotch-dev \
    libeigen3-dev \
    petsc-dev                                       \
    slepc-dev                                       \
    libhdf5-openmpi-dev                                         \
    libnlopt-dev                                                \
    libgsl-dev                                                  \
    libnetcdf-dev libgl2ps-dev libglu1-mesa-dev libsm-dev libxt-dev \
    libfftw3-mpi-dev                                            \
    libxml2-dev   libpugixml-dev                                          \
    libgmsh-dev gmsh                                       \
    bison flex                                              \
    doxygen                                   \
    transfig imagemagick                                    \
    libtbb-dev                                  \
    libann-dev libglpk-dev                                 \
    libbz2-dev libzip-dev                                       \
    libbson-dev                                                 \
    libmongoc-dev                                               \
    libmongo-client-dev                                          \
    python3-pymongo                                              \
    libglew-dev                                                  \
    python3-h5py python3-sympy  python3-mpi4py python3-numpy python3-petsc4py-real python3-slepc4py-real  python3-venv   \
    rsync \
    gdb\
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get -qq update && \
    apt-get -y --no-install-recommends -o APT::Install-Suggests=false install \
    ruby-progressbar                                            \
    ruby-tilt                                                   \
    asciidoctor ruby-asciidoctor-pdf                                                 \
    docker.io jsonlint \
    man jq curl ruby ruby-dev \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


ENV FEELPP_DEP_INSTALL_PREFIX /usr/local



