# make sure that mpi4py is not installed
RUN apt-get -qq update  \
    && apt-get -y --force-yes upgrade  \
    && apt-get -y --force-yes remove python3-mpi4py\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && pip3 install --upgrade mpi4py numpy

