RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    software-properties-common wget
    
RUN add-apt-repository ppa:ubuntu-toolchain-r/test

RUN (for deb in deb; do echo "$deb http://apt.llvm.org/eoan/ llvm-toolchain-eoan-10 main"; done |  tee /etc/apt/sources.list.d/llvm-toolchain.list)
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add - && apt -qq update 
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install tzdata
RUN apt-get -qq update && \
  apt-get --no-install-recommends -y --force-yes install \
           quilt debhelper                                    \
           cmake                                            \
           ssh git-lfs  \           
           clang++-9 g++-8 sudo                                      \
           dh-python                                                   \
           python3 python3-dev python3-setuptools python3-sympy     \
	       chrpath                                                 \
	       libboost1.67-all-dev                                    \
           libcln-dev                                                  \
           libpetsc-real3.11-dev                                       \
           libslepc-real3.11-dev                                       \           
           libhdf5-openmpi-dev                                         \
           libnlopt-dev                                                \
           libgsl-dev                                                  \
           libnetcdf-dev libgl2ps-dev libglu1-mesa-dev libsm-dev libxt-dev \
           libfftw3-mpi-dev                                            \
	       libxml2-dev                                             \
	       libgmsh-dev gmsh                                       \
	       bison flex                                              \
	       doxygen doxygen-latex                                  \
	       transfig imagemagick                                    \
	       libtbb-dev                                  \
	       libann-dev libglpk-dev                                 \
           libbz2-dev                                                  \
           libbson-dev                                                 \
           libmongoc-dev                                               \
           mongodb-clients                                             \
           mongodb-server                                              \
           libmongoclient-dev                                          \
           python-pymongo                                              \
           ruby-progressbar                                            \
           ruby-tilt                                                   \
           asciidoctor                                                 \
           libglew-dev                                                  \
           docker.io jsonlint \
           man jq curl ruby ruby-dev \
           gdb lldb-9\           
           libgmsh4 python3-sympy  python3-mpi4py python3-numpy      \
    && apt-get -y --force-yes install clang-10 clang++-10 \                                 
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60 \
    && update-alternatives --set gcc "/usr/bin/gcc-9" \
    && update-alternatives --set g++ "/usr/bin/g++-9" \
    && update-alternatives --set cc /usr/bin/gcc \
    && update-alternatives --set c++ /usr/bin/g++ \         
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV FEELPP_DEP_INSTALL_PREFIX /usr/local


