# FROM fedora:36

RUN    dnf install -y redhat-lsb-core sudo emacs-nox clang cmake git ruby libcurl-devel jq\
    cln-devel \
    openmpi-devel \
    python3-devel \ 
    boost-devel boost-openmpi-devel \
    MUMPS-openmpi-devel metis-devel \
    petsc-devel  petsc-openmpi-devel python3-petsc-openmpi \
    gmsh gmsh-devel hdf5-openmpi-devel \
    libzip-devel openssl-devel\
    python3-mpi4py-openmpi python3-sympy \
    && dnf clean all \
    && echo ". /etc/profile.d/modules.sh" >> $HOME/.bashrc \
    && echo "module load mpi/openmpi-x86_64" >> $HOME/.bashrc 
RUN    dnf install -y sudo && dnf clean all
# RUN dnf install -y  \
#    curl jq openssl-devel libffi-devel python3 python3-virtualenv python3-devel python3-pip nodejs && \
#     curl -sSL https://get.docker.com/ | sh

