RUN sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu\//http:\/\/miroir.univ-lorraine.fr\/ubuntu\//' /etc/apt/sources.list

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
RUN apt-get -qq update && \
    apt-get -y --force-yes install  tzdata software-properties-common \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get -qq update && \
  apt-get -yq install \
           quilt debhelper                                    \
           tree ne                                              \
           cmake                                             \
           ssh git-lfs                                                 \
           clang g++  sudo             \
           dh-python                                                   \
           python3 python3-dev python3-setuptools python3-sympy python3-pytest python3-gmsh python3-plotly python3-sklearn-pandas  python3-tqdm  \
	       chrpath                                                 \
	       libboost-all-dev                                    \
           libcln-dev                                                  \
           libmetis-dev libscotch-dev \
           libeigen3-dev \
           petsc-dev                                       \
           slepc-dev                                       \           
           libhdf5-openmpi-dev                                         \
           libnlopt-dev                                                \
           libgsl-dev                                                  \
           libnetcdf-dev libgl2ps-dev libglu1-mesa-dev libsm-dev libxt-dev \
           libfftw3-mpi-dev                                            \
	       libxml2-dev                                             \
	       libgmsh-dev gmsh                                       \
	       bison flex                                              \
	       doxygen doxygen-latex                                  \
	       transfig imagemagick                                    \
	       libtbb-dev                                  \
	       libann-dev libglpk-dev                                 \
           libbz2-dev libzip-dev                                       \
           libbson-dev                                                 \
           libmongoc-dev                                               \
           libmongoclient-dev                                          \
           python3-pymongo                                              \
           ruby-progressbar                                            \
           ruby-tilt                                                   \
           asciidoctor ruby-asciidoctor-pdf                                                 \
           libglew-dev                                                  \
           python3-h5py python3-sympy  python3-mpi4py python3-numpy python3-petsc4py-real python3-slepc4py-real  python3-venv   \
	   rsync \
           docker.io jsonlint \
           man jq curl ruby ruby-dev \
           gdb\
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV FEELPP_DEP_INSTALL_PREFIX /usr/local




