RUN apt-get -qq update && \
    apt-get -yq install \
           mongodb-clients                                             \
           mongodb-server                                              \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV FEELPP_DEP_INSTALL_PREFIX /usr/local




