# Set up user so that we do not run as root
# Changing the password does not work on certain OS and is not needed

# RUN apt-get -qq update && \
#     apt-get -y --force-yes install --no-install-recommends \
#             gosu \
#     && apt-get autoremove \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


#RUN gem install rake github_changelog_generator asciidoctor  asciidoctor-bibtex jekyll jekyll-asciidoc \
# && gem install asciidoctor-latex --pre

RUN echo "export FEELPP_GITHUB_TOKEN=${TOKEN}" >> /etc/bash.bashrc
 
RUN useradd -m -s /bin/bash -G video,docker -u 1002 feelpp && \
    echo "feelpp ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN git clone --depth=1 https://github.com/Bash-it/bash-it.git /usr/local/etc/bash_it

ENV LIBBSON_DIR=/usr
ENV LIBMONGOC_DIR=/usr
ENV OMPI_MCA_btl_vader_single_copy_mechanism=none

ENV HOME /home/feelpp

# Our helper scripts
COPY ctest-to-junit.xsl /usr/local/share/xsltproc/ctest-to-junit.xsl
COPY feelpp.env.sh $HOME/feelpp.env.sh
COPY feelpp.conf.sh $HOME/feelpp.conf.sh
COPY feelpp.env.sh /usr/local/etc/feelpp.env.sh
COPY feelpp.conf.sh /usr/local/etc/feelpp.conf.sh
COPY start.sh /usr/local/bin/start.sh
COPY start-user.sh /usr/local/bin/start-user.sh
COPY bashrc.feelpp /usr/local/etc/bashrc.feelpp
COPY WELCOME $HOME/WELCOME
RUN ls /usr/local/etc/

RUN chown -R feelpp.feelpp $HOME/WELCOME \
 && chown -R feelpp.feelpp $HOME/feelpp.conf.sh \
 && chown -R feelpp.feelpp $HOME/feelpp.env.sh 

#ENTRYPOINT ["/sbin/my_init","--quiet","--","sudo","-u","feelpp","/bin/sh","-c"]
#ENTRYPOINT ["/sbin/my_init","--quiet","--","sudo","-u","feelpp","/bin/sh","-c"]
#CMD ["/usr/local/bin/start.sh"]


