# Boost
ENV BOOST_VERSION 1.67.0
ENV BOOST_DIR boost_1_67_0
RUN \
    cd /tmp \
    && wget http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/${BOOST_DIR}.tar.bz2/download -O ${BOOST_DIR}.tar.bz2 \
    && tar xjf ${BOOST_DIR}.tar.bz2 \
    && cd ${BOOST_DIR} \
    && echo "using mpi : /usr/bin/mpicxx : <include>/usr/include/mpi <define>MPICH_SKIP_MPICXX ;" >> user-config.jam \
    && echo "" >> user-config.jam \
    && echo "using python : : /usr/bin/python3 ;" >> user-config.jam \
    && echo "" >> user-config.jam \
    && ./bootstrap.sh \
    && ./bjam -j20 install \
      --layout=tagged \
      --prefix=${FEELPP_DEP_INSTALL_PREFIX} \
      --user-config=user-config.jam \
      variant=release \
      threading=multi \
      link=shared \
    && rm -rf /tmp/* 

