# Use a base image with Spack pre-installed, or choose a base image and install Spack manually
FROM spack/ubuntu-jammy

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    python3-setuptools \
    rsync \
    libblas-dev \
    liblapack-dev \
    sudo \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Clang via Spack
RUN spack install -j40 llvm \
    && spack clean -a

# Install MPICH via Spack
RUN spack install -j40 mpich \
    && spack clean -a

# Install HDF5 and MUMPS via Spack using MPICH
RUN spack install -j40 hdf5 +mpi ^mpich \
    && spack install -j40 mumps +scotch ~metis +mpi ^mpich \
    && spack clean -a

# Install Gmsh via Spack
RUN spack install -j40 gmsh +oce +hdf5 ^/$(spack find --format "{hash:7}" hdf5)\
    && spack clean -a

# Install Boost with MPI support, using MPICH
RUN spack install -j40 boost +regex+date_time+filesystem+iostreams+mpi+multithreaded+program_options+serialization+shared+system+test  ^mpich \
    && spack clean -a

# Install PETSc with MPI support
RUN spack install -j40 petsc +mumps ^/$(spack find --format "{hash:7}" mumps) +mpi ^mpich \
    && spack clean -a

# Install SLEPc
RUN spack install -j40 slepc ^/$(spack find --format "{hash:7}" petsc)  \
    && spack clean -a

# Install Python packages via Spack
RUN spack install -j40 python  \
    && spack clean -a

RUN spack install -j40 py-mpi4py ^mpich\
    && spack clean -a
RUN spack install -j40 py-petsc4py ^/$(spack find --format "{hash:7}" petsc)\
    && spack clean -a
RUN spack install -j40 py-slepc4py ^/$(spack find --format "{hash:7}" slepc)\
    && spack clean -a

RUN spack install -j10 py-sympy\
    && spack clean -a
RUN spack install -j10 py-pytest\
    && spack clean -a
#RUN spack install -j40 py-plotly
#RUN spack install -j40 py-scikit-learn
RUN spack install -j10 py-pandas\
    && spack clean -a
RUN spack install -j10 py-tqdm\
    && spack clean -a
RUN spack install -j10 py-h5py\
    && spack clean -a
RUN spack install -j10 py-numpy\
    && spack clean -a

RUN spack install -j10 libzip \
    && spack clean -a
RUN spack install -j10 cmake \
    && spack clean -a
RUN spack install -j10 ninja \
    && spack clean -a
RUN spack install -j10 git \
    && spack clean -a
RUN spack install -j10 curl \
    && spack clean -a
RUN spack install -j10 wget \
    && spack clean -a
RUN spack install -j10 rsync \
    && spack clean -a

RUN useradd -m devuser
# Set password for devuser (you may want to use a more secure method for setting the password)
RUN echo "devuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Set the user to 'devuser'
USER devuser

# Set the working directory to the user's home directory
WORKDIR /home/devuser

# Install Bash-it
RUN git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it \
    && ~/.bash_it/install.sh \
    && echo "source /opt/spack/share/spack/bash/spack-completion.bash" >> ~/.bashrc


RUN echo 'packages=(mpich hdf5/vc43gg7 mumps gmsh boost petsc slepc python py-mpi4py py-petsc4py py-slepc4py \
                    py-sympy py-pytest py-pandas py-tqdm py-h5py py-numpy/wlkev44 \
                    libzip cmake ninja git curl wget rsync)' >> .bashrc \
    && echo 'for package in "${packages[@]}"; do' >> .bashrc \
    && echo '  echo "Loading package: $package..."' >> .bashrc \
    && echo '  spack load $package' >> .bashrc \
    && echo 'done' >> .bashrc 

# Set the default command to launch when starting the container
#CMD ["/bin/bash"]
