RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    software-properties-common python-software-properties lsb-release \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    
#RUN add-apt-repository 'deb http://ubuntu.openturns.org yakkety main'
#RUN (for deb in deb; do echo "$deb http://ubuntu.openturns.org `lsb_release -cs` main"; done | sudo tee /etc/apt/sources.list.d/openturns.list)
RUN apt-get -qq update && \
    apt-get -y --force-yes install \
         xauth cmake flex gcc-6 g++-6 clang-3.9 clang++-3.9  git ipython3 openmpi-bin pkg-config \
         bash-completion \
         emacs24 emacs vim nano \      
         wget bison sudo \
         libbz2-dev \
         automake autoconf libtool libboost-all-dev \
         doxygen \
         libopenblas-dev libcln-dev libcppunit-dev \
         libgsl-dev \
         libpetsc3.7-dev libslepc3.7-dev liblapack-dev libmpfr-dev \
         libopenmpi-dev libann-dev libglpk-dev \
         python3-dev libhwloc-dev libvtk6-dev libpcre3-dev \
         libhdf5-openmpi-dev libeigen3-dev libcgal-dev \
         python3-numpy python3-six python3-ply \
         python3-h5py python3-urllib3 xterm tmux screen \
         python3-pip \
         gmsh libgmsh-dev \
         mongodb-server mongodb-clients libmongoc-dev libbson-dev \
         libsundials-serial-dev \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

