RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    software-properties-common 
    
# RUN add-apt-repository ppa:ubuntu-toolchain-r/test

#RUN (for deb in deb deb-src; do echo "$deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"; done |  tee /etc/apt/sources.list.d/llvm-toolchain.list)
#RUN apt -qq update && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install tzdata
RUN apt-get -qq update && \
  apt-get -y --force-yes install \
  quilt  debhelper \
  cmake \
  ssh git-lfs sudo \
           clang-7 \
           dh-python \
           python3  python3-dev  python3-setuptools  python3-sympy python3-pytest python3-gmsh python3-plotly python3-sklearn-pandas \
	       chrpath \
	       libboost1.67-all-dev  \
           libcln-dev \
           libpetsc-real3.10-dev \
           slepc-dev \
           libhdf5-openmpi-dev \
           libnlopt-dev \
           libgsl-dev \
           libnetcdf-dev  libgl2ps-dev  libglu1-mesa-dev  libsm-dev  libxt-dev \
           libfftw3-mpi-dev \
	       libxml2-dev \
	       wget  libgmsh-dev  gmsh \
	       bison flex \
	       doxygen  doxygen-latex \
	       transfig imagemagick \
	       libtbb-dev \
	       libann-dev  libglpk-dev \
           libbz2-dev \
           libbson-dev \
           libmongoc-dev \
           mongo-tools \
           libmongoclient-dev            \
           python-pymongo \
           ruby-progressbar \
           ruby-tilt \
           asciidoctor \
           libglew-dev\
           python3-sympy  python3-mpi4py python3-numpy      \
           docker.io jsonlint \
           man jq curl ruby ruby-dev \
           gdb lldb-7\           
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV FEELPP_DEP_INSTALL_PREFIX /usr/local



