FROM fedora:37

RUN    dnf install -y sudo emacs-nox clang cmake git ruby libcurl-devel\
       cln-devel \
       openmpi-devel \
       python3-devel \ 
       boost-devel boost-openmpi-devel \
       MUMPS-openmpi-devel metis-devel \
       petsc-devel  petsc-openmpi-devel python3-petsc-openmpi \
       gmsh gmsh-devel hdf5-openmpi-devel \
       libzip-devel openssl-devel\
       python3-mpi4py-openmpi python3-sympy \
      && dnf clean all \
      && echo ". /etc/profile.d/modules.sh" >> $HOME/.bashrc \
      && echo "module load mpi/openmpi-x86_64" >> $HOME/.bashrc 
