RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    software-properties-common 
    
# RUN add-apt-repository ppa:ubuntu-toolchain-r/test

#RUN (for deb in deb deb-src; do echo "$deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"; done |  tee /etc/apt/sources.list.d/llvm-toolchain.list)
#RUN apt -qq update && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install tzdata
RUN apt-get -qq update && \
  apt-get -y install \
           quilt debhelper                                    \
           cmake                                             \
           ssh git-lfs                                                 \
           clang-10 clang++-10 g++  sudo             \
           dh-python                                                   \
           python3 python3-dev python3-setuptools python3-sympy python3-pytest python3-gmsh python3-plotly python3-sklearn-pandas  \
	       chrpath                                                 \
	       libboost1.67-all-dev                                    \
           libcln-dev                                                  \
           libmetis-dev                                                \
           petsc-dev                                       \
           slepc-dev                                       \           
           libhdf5-openmpi-dev                                         \
           libnlopt-dev                                                \
           libgsl-dev                                                  \
           libnetcdf-dev libgl2ps-dev libglu1-mesa-dev libsm-dev libxt-dev \
           libfftw3-mpi-dev                                            \
	       libxml2-dev                                             \
	       libgmsh-dev gmsh                                       \
	       bison flex                                              \
	       doxygen doxygen-latex                                  \
	       transfig imagemagick                                    \
	       libtbb-dev                                  \
	       libann-dev libglpk-dev                                 \
           libbz2-dev                                                  \
           libbson-dev                                                 \
           libmongoc-dev                                               \
           mongodb-clients                                             \
           mongodb-server                                              \
           libmongoclient-dev                                          \
           python3-pymongo                                              \
           ruby-progressbar                                            \
           ruby-tilt                                                   \
           asciidoctor ruby-asciidoctor-pdf                                                 \
           libglew-dev                                                  \
           python3-sympy  python3-mpi4py python3-numpy python3-petsc4py-real python3-slepc4py-real      \
           docker.io jsonlint \
           man jq curl ruby ruby-dev \
           gdb\
           libscotch-dev\
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV FEELPP_DEP_INSTALL_PREFIX /usr/local




