# Set up user so that we do not run as root
# Changing the password does not work on certain OS and is not needed

# install docker and asciidoctor related tool
RUN apt-get -qq update && \
    apt-get -y --force-yes install \
            docker.io jsonlint \
            man jq curl ruby ruby-dev \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install git-lfs
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
    && apt-get install git-lfs
    
RUN apt-get -qq update && \
    apt-get -y --force-yes install \
            gosu \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN gem install rake github_changelog_generator asciidoctor  asciidoctor-bibtex jekyll jekyll-asciidoc \
 && gem install asciidoctor-latex --pre

# echo "feelpp:docker" | chpasswd && \
RUN useradd -m -s /bin/bash -G sudo,video,docker -u 999 feelpp && \
    echo "feelpp ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN echo /opt/qt56/bin/qt56-env.sh >> /etc/bash.bashrc \
 && echo /opt/qt56/lib  > /etc/ld.so.conf.d/qt56.conf \
 && ldconfig

RUN git clone --depth=1 https://github.com/Bash-it/bash-it.git /usr/local/etc/bash_it

ENV HOME /home/feelpp

# Our helper scripts
COPY feelpp.env.sh $HOME/feelpp.env.sh
COPY feelpp.conf.sh $HOME/feelpp.conf.sh
COPY feelpp.env.sh /usr/local/etc/feelpp.env.sh
COPY feelpp.conf.sh /usr/local/etc/feelpp.conf.sh
COPY start.sh /usr/local/bin/start.sh
COPY start-user.sh /usr/local/bin/start-user.sh
COPY bashrc.feelpp /usr/local/etc/bashrc.feelpp
COPY WELCOME $HOME/WELCOME
RUN ls /usr/local/etc/

RUN chown -R feelpp.feelpp $HOME/WELCOME \
 && chown -R feelpp.feelpp $HOME/feelpp.conf.sh \
 && chown -R feelpp.feelpp $HOME/feelpp.env.sh 

#ENTRYPOINT ["/sbin/my_init","--quiet","--","sudo","-u","feelpp","/bin/sh","-c"]
#ENTRYPOINT ["/sbin/my_init","--quiet","--","sudo","-u","feelpp","/bin/sh","-c"]
CMD ["/usr/local/bin/start.sh"]


