# only in 36 for now, because not available in 37
RUN dnf install -y 'dnf-command(config-manager)'

# COPY docker-ce.repo /etc/yum.repos.d/docker-ce.repo
#    && curl -sSL https://get.docker.com/ | sh
RUN dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
RUN dnf makecache && dnf install -y docker-ce docker-ce-cli containerd.io
