RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    software-properties-common 
    
# RUN add-apt-repository ppa:ubuntu-toolchain-r/test

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install tzdata
RUN apt-get -qq update && \
  apt-get -y --force-yes install \
           quilt debhelper                                    \
           cmake                                             \
           ssh git-lfs                                                 \
           clang g++  sudo             \
           dh-python                                                   \
           python3 python3-dev python3-setuptools python3-sympy        \
	       chrpath                                                 \
           libcurl4-openssl-dev                                         \
	       libboost1.71-all-dev                                    \
           libcln-dev                                                  \
           libmetis-dev                                                \
           petsc-dev                                       \
           slepc-dev                                       \           
           libhdf5-openmpi-dev                                         \
           libnlopt-dev                                                \
           libgsl-dev                                                  \
           libnetcdf-dev libgl2ps-dev libglu1-mesa-dev libsm-dev libxt-dev \
           libfftw3-mpi-dev                                            \
	       libxml2-dev                                             \
	       libgmsh-dev gmsh                                       \
	       bison flex                                              \
	       doxygen doxygen-latex                                  \
	       transfig imagemagick                                    \
	       libtbb-dev                                  \
	       libann-dev libglpk-dev                                 \
           libbz2-dev                                                  \
           libbson-dev                                                 \
           libmongoc-dev                                               \
           mongodb-clients                                             \
           mongodb-server                                              \
           libmongoclient-dev                                          \
           python3-pymongo                                              \
           ruby-progressbar                                            \
           ruby-tilt                                                   \
           asciidoctor ruby-asciidoctor-pdf                                                 \
           libglew-dev                                                  \
           python3-sympy  python3-mpi4py python3-numpy      \
           docker.io jsonlint \
           man jq curl ruby ruby-dev \
           gdb lldb-9\
    && apt-get -y --force-yes install clang-8 clang++-8 \
    && apt-get -y --force-yes install clang-10 clang++-10 \                                 
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60 \
    && update-alternatives --set gcc "/usr/bin/gcc-9" \
    && update-alternatives --set g++ "/usr/bin/g++-9" \
    && update-alternatives --set cc /usr/bin/gcc \
    && update-alternatives --set c++ /usr/bin/g++ \         
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV FEELPP_DEP_INSTALL_PREFIX /usr/local


