# Install PETSc from source
ENV PETSC_VERSION 3.8.2
RUN \
    cd /tmp \
    && wget -nc http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-${PETSC_VERSION}.tar.gz \
    && tar -xf petsc-${PETSC_VERSION}.tar.gz \
    && cd petsc-${PETSC_VERSION} \
    && ./configure --COPTFLAGS="-O2" \
                --CXXOPTFLAGS="-O2" \
                --FOPTFLAGS="-O2" \
                --with-blas-lib=/usr/lib/libopenblas.a --with-lapack-lib=/usr/lib/liblapack.a \
                --with-c-support \
                --with-debugging=0 \
                --with-shared-libraries \
                --download-suitesparse \
                --download-scalapack \
                --download-metis \
                --download-parmetis \
                --download-ptscotch \
                --download-hypre \
                --download-mumps \
                --download-blacs \
                --download-spai \
                --download-ml \
                --prefix=${FEELPP_DEP_INSTALL_PREFIX} \
     && make \
     && make install \
     && rm -rf /tmp/* 

# Install SLEPc from source
ENV SLEPC_VERSION 3.8.1
RUN \
    cd /tmp \
    && export PETSC_DIR=${FEELPP_DEP_INSTALL_PREFIX} \
    && wget -nc http://slepc.upv.es/download/distrib/slepc-${SLEPC_VERSION}.tar.gz -O slepc-${SLEPC_VERSION}.tar.gz \
    && tar -xf slepc-${SLEPC_VERSION}.tar.gz \
    && cd slepc-${SLEPC_VERSION} \
    && ./configure --prefix=${FEELPP_DEP_INSTALL_PREFIX} \
    && make \
    && make install \
    && rm -rf /tmp/* 


ENV SLEPC_DIR ${FEELPP_DEP_INSTALL_PREFIX}
ENV PETSC_DIR ${FEELPP_DEP_INSTALL_PREFIX}
