SHELL ["/bin/bash", "-c"]
RUN json=$(curl -s "https://api.github.com/repos/Kitware/CMake/releases"); \
    echo "JSON: $json"; \
    latest_tag=$(echo $json | jq -r '.[] | select(.prerelease==false).tag_name' | sort --unique --version-sort | grep -v "rc" | tail -1); \
    echo "Latest tag: $latest_tag"; \
    sh_url=$(echo $json | jq -r ".[] | select(.tag_name==\"${latest_tag}\").assets[].browser_download_url | select(endswith(\"inux-x86_64.sh\"))"); \
    echo "Download URL: $sh_url"; \
    curl -sL ${sh_url} -o cmakeinstall.sh; \
    chmod +x cmakeinstall.sh; \
    ./cmakeinstall.sh --prefix=/usr/local --exclude-subdir; \
    rm cmakeinstall.sh
SHELL ["/bin/sh", "-c"]
