RUN apt-get -qq update  \
    && apt-get -y --force-yes upgrade  \
    && apt-get -y --force-yes install python-pymongo \
    && apt-get -y --force-yes autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    
