FROM fedora:36

RUN    dnf install -y sudo emacs-nox clang cmake git \
       automake autoconf libtool \
       cln-devel \
       openmpi-devel \
       boost-devel boost-openmpi-devel \
       petsc-devel  petsc-openmpi-devel gmsh-devel \
       hdf5-devel ann-devel glpk-devel \
    && dnf clean all

# how to use mpi: https://docs.fedoraproject.org/en-US/neurofedora/mpi/
# export
ENV arch=x86_64
RUN module load mpi/openmpi-$arch # $arch is the architecture, for example x86_64
