FROM phusion/baseimage:latest
MAINTAINER Feel++ Support <support@feelpp.org>

# Install build environment
RUN apt-add-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
RUN apt-add-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main'

RUN apt-get -qq update && \
    apt-get -y --force-yes install \
    	 xauth cmake flex g++-4.9 clang-3.8 gfortran git ipython openmpi-bin pkg-config \
         wget bison sudo \
         libbz2-dev \
         automake autoconf libtool \
         libopenblas-dev libcln-dev libcppunit-dev \
         libeigen3-dev liblapack-dev libmpfr-dev \
         libopenmpi-dev libann-dev libglpk-dev \
         python-dev libhwloc-dev libvtk6-dev libpcre3-dev \
         libhdf5-openmpi-dev libeigen3-dev libcgal-dev \
         python-numpy python-vtk6 python-six python-ply \
         python-h5py python-urllib3 xterm tmux screen \
         libphonon-dev libphonon4 qt4-dev-tools libqt4-core libqt4-gui qt4-qmake libxt-dev libqt4-opengl-dev mesa-common-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/bin/bash"]
