name: Feelpp Toolboxes Docker

on: 
  repository_dispatch:
    types: [pkg-feelpp-toolboxes-published]
  push: 
    paths:
      - 'feelpp-toolboxes/Docketfile'
      - '.github/workflows/feelpp-toolboxes.yml'

jobs:

  activate:
    runs-on: self-docker
    if: |
      github.repository == 'feelpp/docker' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  deliver:
    if: "!contains(github.event.head_commit.message, 'deliver skip')"
    runs-on: self-docker
    needs: activate
    strategy:
      fail-fast: false
      matrix: 
        include:
          - {service: feelpp-toolboxes, dist: "${{ github.event.client_payload.dist }}", tag: "${{ github.event.client_payload.dist }}", dockerfile: "Dockerfile" }
    name: Build and Push feelpp/${{ matrix.service }}:${{ matrix.dist }}

    steps:
    - uses: actions/checkout@v2.3.4
      with:
#        lfs: true  
        token: ${{ secrets.CR_PAT }}
        submodules: recursive
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1        
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - 
      name: Build ${{ matrix.service }}:${{ matrix.tag }}
      uses: docker/build-push-action@v2
      with: 
        context: ./${{ matrix.service }}/
        tags: ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.tag }}
        file: ${{ matrix.service }}/${{ matrix.dockerfile }}
        build-args: VARIANT=${{ matrix.tag }}
        load: true
    -
      name: Push ${{ matrix.service }}:${{ matrix.tag }}
      run: |
        docker push ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.tag }}