name: Feelpp Docker

on: 
  repository_dispatch:
    types: [pkg-feelpp-published]
#  push: 
#    paths:
#      - 'feelpp/Dockerfile'
#      - '.github/workflows/feelpp.yml'

jobs:

  activate:
    runs-on: self-docker
    if: |
      github.repository == 'feelpp/docker' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  deliver:
    if: "!contains(github.event.head_commit.message, 'deliver skip')"
    runs-on: self-docker
    needs: activate
    strategy:
      fail-fast: false
      matrix: 
        include:
          - { 
              service: "${{ github.event.client_payload.component }}", 
              dist: "${{ github.event.client_payload.dist }}", 
              version: "${{ github.event.client_payload.version }}", 
              tag: "v${{ github.event.client_payload.version }}-${{ github.event.client_payload.dist }}", 
              dockerfile: "Dockerfile-${{ github.event.client_payload.dist }}" 
            }
    name: Build and Push feelpp/${{ matrix.service }}:${{ matrix.tag }}

    steps:
    - uses: actions/checkout@v2.3.4
      with:
#        lfs: true  
        token: ${{ secrets.CR_PAT }}
        submodules: recursive
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1        
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - 
      name: Build ${{ matrix.service }}:${{ matrix.tag }}
      uses: docker/build-push-action@v2
      if: ${{ matrix.service == 'feelpp' }}
      with: 
        context: ./${{ matrix.service }}/
        tags: ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.tag }}
        file: ${{ matrix.service }}/${{ matrix.dockerfile }}
        push: true
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
    - 
      name: Build ${{ matrix.service }}-dev:${{ matrix.tag }}
      uses: docker/build-push-action@v2
      with: 
        context: ./${{ matrix.service }}-dev/
        tags: ghcr.io/feelpp/${{ matrix.service }}-dev:${{ matrix.tag }}
        file: ${{ matrix.service }}-dev/${{ matrix.dockerfile }}
        build-args: TAG=${{ matrix.tag }}
        push: true
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
