name: Feelpp Docker
run-name: "[${{ github.event.client_payload.dist }}${{ inputs.flavor }-${{ github.event.client_payload.version }}${{ inputs.version }]"
on: 
  repository_dispatch:
    types: [pkg-feelpp-published]
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor of the distribution'  
        required: true
        default: ubuntu
      dist:
        description: 'Name of the distribution'  
        required: true
        default: jammy
      version:
        description: 'Version of Feel++ packages'  
        required: true


jobs:

  activate:
    runs-on: self-docker
    if: |
      github.repository == 'feelpp/docker' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  deliver:
    if: ${{ github.event_name == 'repository_dispatch' && !contains(github.event.head_commit.message, 'deliver skip') }} 
    runs-on: self-docker
    needs: activate
    strategy:
      fail-fast: false
      matrix: 
        include:
          - { 
              service: "${{ github.event.client_payload.component }}", 
              dist: "${{ github.event.client_payload.dist }}", 
              version: "${{ github.event.client_payload.version }}", 
              tag: "v${{ github.event.client_payload.version }}-${{ github.event.client_payload.dist }}", 
              dockerfile: "Dockerfile-${{ github.event.client_payload.dist }}", 
              dockerfile-dev: "Dockerfile" 
            }
    name: Build and Push feelpp/${{ matrix.service }}:${{ matrix.tag }}

    steps:
    - uses: actions/checkout@v2.3.4
      with:
#        lfs: true  
        token: ${{ secrets.CR_PAT }}
        submodules: recursive
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2        
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - 
      name: Build ${{ matrix.service }}:${{ matrix.tag }}
      uses: docker/build-push-action@v3
      if: ${{ matrix.service == 'feelpp' }}
      with: 
        context: ./${{ matrix.service }}/
        tags: ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.tag }},ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.dist }}
        file: ${{ matrix.service }}/${{ matrix.dockerfile }}
        push: true
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
    - 
      name: Build ${{ matrix.service }}-dev:${{ matrix.tag }}
      uses: docker/build-push-action@v3
      with: 
        context: ./${{ matrix.service }}-dev/
        tags: ghcr.io/feelpp/${{ matrix.service }}-dev:${{ matrix.tag }},ghcr.io/feelpp/${{ matrix.service }}-dev:${{ matrix.dist }}
        file: ${{ matrix.service }}-dev/${{ matrix.dockerfile-dev }}
        build-args: TAG=${{ matrix.tag }}
        push: true
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}

  manual:
    if: ${{ github.event_name == 'workflow_dispatch' && !contains(github.event.head_commit.message, 'deliver skip') }} 
    runs-on: self-docker
    needs: activate
    strategy:
      fail-fast: false
      matrix: 
        include:
          - { 
              service: "feelpp", 
              dist: "${{ inputs.dist }}", 
              version: "${{ inputs.version }}", 
              tag: "v${{ inputs.version }}-${{ inputs.dist }}", 
              dockerfile: "Dockerfile", 
              dockerfile-dev: "Dockerfile" 
            }
    name: Build and Push feelpp/${{ matrix.service }}:${{ matrix.tag }}

    steps:
    - uses: actions/checkout@v2.3.4
      with:
#        lfs: true  
        token: ${{ secrets.CR_PAT }}
        submodules: recursive
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - 
      name: Build ${{ matrix.service }}:${{ matrix.tag }}
      uses: docker/build-push-action@v3
      if: ${{ matrix.service == 'feelpp' }}
      with: 
        context: ./${{ matrix.service }}/
        tags: ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.tag }},ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.dist }}
        file: ${{ matrix.service }}/${{ matrix.dockerfile }}
        push: true
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
    - 
      name: Build ${{ matrix.service }}-dev:${{ matrix.tag }}
      uses: docker/build-push-action@v3
      with: 
        context: ./${{ matrix.service }}-dev/
        tags: ghcr.io/feelpp/${{ matrix.service }}-dev:${{ matrix.tag }},ghcr.io/feelpp/${{ matrix.service }}-dev:${{ matrix.dist }}
        file: ${{ matrix.service }}-dev/${{ matrix.dockerfile-dev }}
        build-args: TAG=${{ matrix.tag }}
        push: true
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
